### PR TITLE
Fixes #37 - Provide more precise kernel version command output

### LINKED ISSUE #37: Describe the output
Wouldn't it be better to describe the output - like:
```bash
echo -n "Patched kernel version:"
/usr/bin/kcarectl --uname 
echo -n "Kernel version:"
uname -r
```

_Originally posted by @sbernhard in https://github.com/maccelf/foreman_kernel_care/pull/33#discussion_r1053252294_

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by maccelf** [comment]
Are you sure it works correctly? I mean [here](https://github.com/maccelf/foreman_kernel_care/blob/c49df4242abab1e8b50d5f8b7724c06d144d6a34/app/controllers/concerns/foreman_kernel_care/foreman_tasks.rb#LL12C89-L12C89) we parse the output, and I am not sure that we can just leave this file without any update.

**Comment by nadjaheitmann** [comment]
Good catch, let me have another look.

**Comment by nadjaheitmann** [comment]
@maccelf I also found this file which needs changing if the name of the template is changed: https://github.com/maccelf/foreman_kernel_care/blob/master/db/seeds.d/100_assign_features_with_templates.rb Why are there two seed files for the job templates?

**Comment by maccelf** [comment]
@nadjaheitmann Yes, you are right, we should change these files too.
`100_assign_features_with_templates.rb` is assign features with templates and `70_job_templates.rb` just initiliaze job templates. Maybe we can join these files but in [foreman_remote_execution](https://github.com/theforeman/foreman_remote_execution/tree/cbe138493e7d5e6e4085e571ef599713df17f565/db/seeds.d) they are also split into 2 files.

**Comment by nadjaheitmann** [comment]
I don't think we need the `100_assign_features_with_templates.rb` one. [Here](https://github.com/theforeman/foreman_remote_execution/commit/411026b7a883f77a1c3b5142b28237540ced61e2) is the commit why it was added in `foreman_remote_execution`. I don't think that we need something like this for this plugin, do we?

**Comment by maccelf** [comment]
Here we call template via feature
https://github.com/maccelf/foreman_kernel_care/blob/c49df4242abab1e8b50d5f8b7724c06d144d6a34/app/models/concerns/foreman_kernel_care/host_managed_extensions.rb#L18
https://github.com/maccelf/foreman_kernel_care/blob/c49df4242abab1e8b50d5f8b7724c06d144d6a34/app/models/concerns/foreman_kernel_care/host_managed_extensions.rb#L5

So we need this file to assign job templates with it.

**Comment by nadjaheitmann** [comment]
Okay, thanks, I see. I will have another look at the parsing of the file, then.

**Comment by nadjaheitmann** [comment]
@maccelf I finally got to have a look at this again and fixed it. Can you check, please?

**Review by maccelf — APPROVED** [review]

**Pull request merged**
